name: tokshop
description: Tokshop.Live.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  flutter_screenutil: ^5.3.1
  ionicons: ^0.2.2
  http: ^0.13.4
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.3
  cached_network_image: ^3.2.0
  image_picker:
  image_cropper: ^3.0.1
  agora_rtc_engine: ^5.3.0
  connectivity_plus: ^3.0.3
  firebase_storage:
#  flutter_facebook_auth: ^5.0.7
  onesignal_flutter: ^3.4.2
  flutter_local_notifications: ^13.0.0
  firebase_dynamic_links: ^5.0.15
  share: ^2.0.4
  flutter_svg: ^2.0.2
  permission_handler: ^10.0.0
  animation_wrappers: ^3.0.0
  flutter_stripe: ^4.0.0
  video_player: ^2.4.4
  chewie: ^1.3.3
  agora_rtm: ^1.1.0
  dart_ipify: ^1.1.1
  csc_picker: ^0.2.6
  url_launcher: ^6.0.2
  flutter_datetime_picker: ^1.5.1
  country_picker: ^2.0.16
  google_sign_in: ^6.0.1
  sign_in_with_apple: ^4.1.0
  shared_preferences: ^2.0.15
  flutter_rating_bar: ^4.0.1
  shimmer: ^2.0.0
  package_info_plus: ^3.0.1
  scroll_snap_list: ^0.9.1

  wakelock: ^0.6.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: Circular
      fonts:
        - asset: assets/fonts/circular/CircularStd-Bold.otf
          weight: 300
        - asset: assets/fonts/circular/CircularStd-Light.otf
          weight: 100
        - asset: assets/fonts/circular/CircularStd-Black.otf
        - asset: assets/fonts/circular/CircularStd-Medium.otf
          weight: 200

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/sounds/